### ISSUE TITLE
Suggestion for bees

### ISSUE THREAD

**Issue by McBossKiller** [Lach01298/MoreBees#1]
You should add bees that create mob drops( this would be good for peaceful players ) and also add bees to the Nether

Example
1st tier:
Flesh bee- Rotten Flesh( releases hunger effect )
Skeletal Bee- bones and maybe bone meal
Spider Bee- string
Nether bee- NetherRack
2nd tier:
skeletal bee + Nether bee = Wither bee - bones and Netherwart

Just an example, hope you get the general idea and can probably do better with it :)

**Comment by Lach01298** [comment]
reasonable idea i might implement it and also there is already a wither bee that produces nether star fragments and a withering bee that produces all the things wither skeletons drop including heads.

**Comment by McBossKiller** [comment]
Wow never even knew :)

**Comment by Lach01298** [comment]
Added a bee that produces string so ....... issue closed.
