### ISSUE TITLE
Crossing Clay + Obsidian bees gives Radiation effect? 

### ISSUE THREAD

**Issue by Giovanni-NL** [Lach01298/MoreBees#12]
This has now happened to me twice.   When trying to create the Prismarine bee by crossing Clay and Obsidian bees in an Ocean biome the resulting drones sometimes get the Radiation effect.  Is this intended?  It does not make sense to me... 

Using MoreBees version 1.10.2-1.1.4

P.S. The effect is not present on any of the bees I am breeding with...

**Comment by Lach01298** [comment]
weird.

**Comment by Lach01298** [comment]
Fixed in 1.1.5
