### ISSUE TITLE
IC2Classic support

### ISSUE THREAD

**Issue by Speiger** [Lach01298/MoreBees#13]
IC2Classic will crash with this mod :(
the reason for it is that IC2Classic has no StoneDust.
Could you add another check for IC2Classic?
IC2Classic has a secondary modid which allows you to detect it.
(and its sharing IC2s id for modcompat)
ModID: "IC2-Classic-Spmod"

**Comment by Lach01298** [comment]
IC2 Classic ? i can't find IC2 classic for 1.10?

**Comment by Speiger** [comment]
IC2Classic is 1.10.2 but not public yet. Its in closed beta but some testers already have it and they found this issue.
I can give you all info if you need it.

**Comment by Lach01298** [comment]
ok

**Comment by Lach01298** [comment]
Is there crushed uranium? if not i can make the uranic bees to produce more uranium ore.

**Comment by Speiger** [comment]
Nope. But the uranium drop exists. Its using the OreDictionary tag: dropUranium. That is what the uranium Ore Drops in classic. oreUranium = the OreBlock Itself. or if you want to have a ingot: ingotUranium
That would work.
Also IC2Classic adds 5 new Uranium Types: Redstone, EnderPearl, Blaze, NetherStar & Charcoal.
These metals apply differend abilities to the reactor.
https://github.com/TinyModularThings/IC2Classic/wiki
The wiki is in its earliest constructions but is beeing done and will be finished before the release.
So you get a view what classic does. (Also the api i provide has a bit more extendet support for some things)
But again. Documentation is still not finalized since the mod is no 100% done because of bugtesting & tweaking is still a thing. But we get close to an end.

**Comment by Lach01298** [comment]
Ok i have made a new beta (1.10.2-1.1.6b). It should be compatible if it isn't tell me.

**Comment by Speiger** [comment]
https://github.com/Lach01298/MoreBees/blob/master/src/main/java/lach_01298/moreBees/recipes/RecipesCentrifuge.java#L36
Em yeah there is a crash possible since you inject a empty OreDict list is with stone dust when classic is only installed.

**Comment by Lach01298** [comment]
sorry i keep forgetting to update git hub so that code isn't up to date.
