### ISSUE TITLE
Disable/Enable ore types that spawn around rocky hives

### ISSUE THREAD

**Issue by belathus** [Lach01298/MoreBees#15]
The modpack I've been working on makes iron ore a lot harder to get (specifically, we're using the Rockhounding oretiers mod that replaces iron ore with various ore types, such as hematite, magnetite, etc.).

Unfortunately, this is partially bypassed by the fact that rocky bee hives spawn with iron ore nearby. Any chance that I could remove this ore or replace it with other ores?

**Comment by Lach01298** [comment]
Sure in the next version i will be adding a config file to go with the mod i put that as an option

**Comment by Lach01298** [comment]
Done
