### ISSUE TITLE
Yellorium bees

### ISSUE THREAD

**Issue by BrainStone** [Lach01298/MoreBees#19]
It would be quite nice to have bees for yellorium from [Extreme Reactors](https://minecraft.curseforge.com/projects/extreme-reactors). Nothing big. Just another bee.

**Comment by Lach01298** [comment]
Isn't yellorium ore dictionared with uranium? that was the case with big reactors.

**Comment by BrainStone** [comment]
I'll have a look at it. I did not think of that tbh

**Comment by Dannerick** [comment]
I checked this out and yellorium ore is not oredicted to oreUranium. It uses oreYellorite and oreYellorium. A yellorium bee is a good candidate going right along side the new resonating bee.

**Comment by Lach01298** [comment]
I couldn't get yellorium bees to work since it seems extreme reactors does its oredic in post initialization which is really weird

**Comment by BrainStone** [comment]
What exactly do you need the oredic for?  
For recipes? As far as I know if you use a oredict recipe it will work straight away regardless of when the oredic gets registered.

**Comment by Dannerick** [comment]
The oredict is the way to get the actual item stack of the material to be produced without having to actually have More Bee depend on the other mod or its api being available when More Bees is built. The ore dictionary is the way to let forge handle all the cross mod compatibility issues.

**Comment by Dannerick** [comment]
I traced through the code and Extreme Reactor does the oredict registration during the init phase. You just need to force More Bees to load after Extreme Reactor ("bigreactors").

**Comment by Dannerick** [comment]
I did a quick test with the mod loaded as I don't normally use Extreme Reactors in my current survival world. Adding "after:bigreactors" to the mod dependencies and re-enabling the check in LoadMods.java, does get the yellorite bee to generate and correctly get generated from mutations.
