### ISSUE TITLE
Proposal for new comb types

### ISSUE THREAD

**Issue by Dannerick** [Lach01298/MoreBees#24]
The metallic and crystal branches need to have their own comb types instead of using the rocky combs. Metallic and crystal combs, when centrifuged would drop wax and metallic or crystal propolis respectfully. This propolis could then either be crafted into or centrifuged to metallic/crystal grains which would be used in a carpenter in differing patterns to get the metal dusts or crystal products. This is a similar process that Forestry uses for ender pearls and silk mesh from bee drops.

**Comment by Lach01298** [comment]
Sounds good to me

**Comment by Dannerick** [comment]
I'll give this work a shot. The coding is pretty straight forward, but I'm terrible at making graphics for models.
