### ISSUE TITLE
Sulfur bees not getting generated

### ISSUE THREAD

**Issue by Dannerick** [Lach01298/MoreBees#30]
I was not getting sulfur bees to get generated even though I have three separate mods that all add sulfur and all register as "dustSulfur". The check for sulfur needs to get moved to the late registration section of LoadMods.java.

You might want to check for "dustSulphur" as well. That is how it is spelled outside the US and some mods use that spelling.

**Comment by Lach01298** [comment]
for 1.3 i changed the load mods so it runs twice one in preinit and init so there is no late mods now it should be fixed
