### ISSUE TITLE
[More Bees 1.3][MC 1.10.2] CTD During Startup

### ISSUE THREAD

**Issue by Alaberti** [Lach01298/MoreBees#31]
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Bees (morebees)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

http://pastebin.com/raw/uBsz1J5E

Forge 2202
Forestry 5.2.17.349

**Comment by Lach01298** [comment]
yeah i've taken 1.3 down for the moment because a found a few bugs

**Comment by Lach01298** [comment]
Fixed

**Comment by Alaberti** [comment]
Thanks for the quick fix!
