### ISSUE TITLE
Diamond Bees do not produce Diamond Fragments

### ISSUE THREAD

**Issue by Xiaminou** [Lach01298/MoreBees#33]
![2017-01-16_17 11 17](https://cloud.githubusercontent.com/assets/8670392/21990388/ec222a8a-dc0e-11e6-99c6-bade59a98521.png)

Recipe say they do but I've gotten a couple of stacks of combs and 0 fragments.

**Comment by Lach01298** [comment]
Read the wiki it says you need diamond blocks under the hive for them to produce fragments

**Comment by Xiaminou** [comment]
I'll admit I didn't know there's a wiki, BUT, it still doesn't work.

![2017-01-17_15 40 21](https://cloud.githubusercontent.com/assets/8670392/22024762/597ed1ca-dccb-11e6-87bb-7a3d1cc56e68.png)

Also I'm assuming you mean Apiary and not Hive.

![2017-01-17_16 12 56](https://cloud.githubusercontent.com/assets/8670392/22026029/d84c6f7c-dccf-11e6-8e41-f1b58a9fe6e9.png)

**Comment by Lach01298** [comment]
It's diamond blocks not ore

**Comment by Lach01298** [comment]
Actually thinking about it i'll make both acceptably for less confusion. (update 1.3.1)

**Comment by Xiaminou** [comment]
Oh my bad, I'm so used to putting ores under crops and stuff to make it grow.
Derping pretty hard.
