### ISSUE TITLE
[1.10.2][1.3.1] net.minecraftforge.fml.common.LoaderExceptionModCrash:

### ISSUE THREAD

**Issue by addrever** [Lach01298/MoreBees#34]
Hello,

I have an issue with more bees loading up in my custom pack.  I have attached the crash-report for your review.

Thanks
[crash-2017-02-18_09.27.55-client.txt](https://github.com/Lach01298/MoreBees/files/785100/crash-2017-02-18_09.27.55-client.txt)

**Comment by Lach01298** [comment]
do any of the mods add silver? and is their a dust? if so which mods?

**Comment by addrever** [comment]
Thank you very much for responding.

There are four mods that add silver.  They do not provide dust that I can see in JEI.

The mods and version are:
Chickens 4.3.2
Railcraft 10.0.1
ProjectRed 4.8.0.17
Mystical Agriculture 1.4.1a

Hope this helps.  Let me know if you need further info.

Cheers.

**Comment by Lach01298** [comment]
1.3.2 might fix it if it doesn't let me know

**Comment by addrever** [comment]
Thank you!
