### ISSUE TITLE
Specialities in alviaries

### ISSUE THREAD

**Issue by DevJohnC** [Lach01298/MoreBees#35]
The speciality produce in this mod requires items above or below a hive, ex: wither skulls on the hive, diamond block below.

Does this work with alviary? I can't produce specialities from an alviary at all.

**Comment by DevJohnC** [comment]
After moving TNT to under the alviary apocalypric bees seem to produce the specialities, so that's all good for those bees that require items beneath the hive.

However I can not get withering or wither bees to produce skulls/star fragments by placing wither skulls on top of the alviary.

**Comment by Lach01298** [comment]
I'll say that is a unintentional "balance" feature.
