### ISSUE TITLE
Suggestion: Fluix Bee

### ISSUE THREAD

**Issue by Kris1432** [Lach01298/MoreBees#39]
Since there are Certus Bees, it would be pretty awesome to get some Fluix Bees in the mod too and possibly some of the Pure Crystals as by products?

Thanks!

**Comment by Lach01298** [comment]
I'm not going to since my main idea of this mod is about base resources i.e. no steel bees because it's made from iron. I do this so you can't skip progression in other mods.
but thanks for the suggestion there always appreciated.
