### ISSUE TITLE
[1.10.2][Forge 2086] Crash on client start up

### ISSUE THREAD

**Issue by Hastling** [Lach01298/MoreBees#4]
http://pastebin.com/aKYzqV1A

**Comment by Lach01298** [comment]
I can't see why this is happening. but the new version 1.1.1 might fix it. if it doesn't tell me and i'll dig deeper.

**Comment by Hastling** [comment]
It didn't appear to fix it, now it's a different issue. http://pastebin.com/8BmwQ0qA

**Comment by Lach01298** [comment]
what mod/mods do you have that add uranium ore?

**Comment by Hastling** [comment]
I had none, I only had TechReborn but after adding IndustrialCraft the crash no longer occurs.

**Comment by Lach01298** [comment]
update 1.1.2 should fix it now
