### ISSUE TITLE
Game crashes when i use the swarmer with a rocky queen

### ISSUE THREAD

**Issue by Gucky2000** [Lach01298/MoreBees#43]
The Game crashes, when i use the swarmer and a new rocky hive is generated. Had to remove the Mod. I liked Extra Bees so much and i'm glad that someone is working on it :-)
Thanks
 
Forgot to tell you, that i am using Minecraft 1.11.2 Version

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  LoadingPlugin (Quark-r1.2-92.jar)
  CorePlugin (FluxedRedstone-2.6.1.59.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  HammerCoreCore (HammerCore_1.11.2-1.6.7.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 5/24/17 7:35 PM
Description: Ticking block entity

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at forestry.core.inventory.InventoryPlain.func_70299_a(InventoryPlain.java:71)
	at forestry.core.inventory.InventoryAdapter.func_70299_a(InventoryAdapter.java:101)
	at forestry.apiculture.inventory.InventoryApiary.wearOutFrames(InventoryApiary.java:80)
	at forestry.apiculture.ApiaryBeeListener.wearOutEquipment(ApiaryBeeListener.java:26)
	at forestry.apiculture.BeeHousingListener.wearOutEquipment(BeeHousingListener.java:27)
	at forestry.apiculture.BeekeepingLogic.doProduction(BeekeepingLogic.java:298)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:274)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:246)
	at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:153)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:87)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at forestry.core.inventory.InventoryPlain.func_70299_a(InventoryPlain.java:71)
	at forestry.core.inventory.InventoryAdapter.func_70299_a(InventoryAdapter.java:101)
	at forestry.apiculture.inventory.InventoryApiary.wearOutFrames(InventoryApiary.java:80)
	at forestry.apiculture.ApiaryBeeListener.wearOutEquipment(ApiaryBeeListener.java:26)
	at forestry.apiculture.BeeHousingListener.wearOutEquipment(BeeHousingListener.java:27)
	at forestry.apiculture.BeekeepingLogic.doProduction(BeekeepingLogic.java:298)
	at forestry.apiculture.BeekeepingLogic.queenWorkTick(BeekeepingLogic.java:274)
	at forestry.apiculture.BeekeepingLogic.doWork(BeekeepingLogic.java:246)
	at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:153)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:87)

-- Block entity being ticked --
Details:
	Name: minecraft:forestry.apiary // forestry.apiculture.tiles.TileApiary
	Block type: ID #1369 (tile.for.apiary // forestry.apiculture.blocks.BlockApiculture)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-182,63,427), Chunk: (at 10,3,11 in -12,26; contains blocks -192,0,416 to -177,255,431), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1369 (tile.for.apiary // forestry.apiculture.blocks.BlockApiculture)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Insel 01
	All players: 1 total; [EntityPlayerMP['Gucky2000'/221, l='Insel 01', x=-183.50, y=63.00, z=424.78]]
	Chunk stats: ServerChunkCache: 1250 Drop: 0
	Level seed: -3212458747512914983
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"archipelago","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (-73,64,-50), Chunk: (at 7,4,14 in -5,-4; contains blocks -80,0,-64 to -65,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1369453 game time, 1468525 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 100674 (now: false), thunder time: 119181 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2019584040 bytes (1926 MB) / 6014107648 bytes (5735 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 68
	FML: MCP 9.38 Powered by Forge 13.20.0.2304 Optifine OptiFine_1.11.2_HD_U_B9 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJAAAA	forge{13.20.0.2304} [Minecraft Forge] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r108} [Actually Additions] (ActuallyAdditions-1.11.2-r108.jar) 
	UCHIJAAAA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
	UCHIJAAAA	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	aquaculture{1.5.0} [Aquaculture] (Aquaculture-1.11.2-1.5.0.33.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCHIJAAAA	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar) 
	UCHIJAAAA	quark{r1.2-92} [Quark] (Quark-r1.2-92.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	baubles{1.4.4} [Baubles] (Baubles-1.11-1.4.4.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-6.0.1.jar) 
	UCHIJAAAA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCHIJAAAA	bibliocraft{2.3.0} [BiblioCraft] (BiblioCraft[v2.3.0][MC1.11.2].jar) 
	UCHIJAAAA	hammercore{1.6.7} [Hammer Core] (HammerCore_1.11.2-1.6.7.jar) 
	UCHIJAAAA	biomepainttools{1.0.4} [Biome Paint Tools] (BiomePaintTools_1.11.2-1.0.4.jar) 
	UCHIJAAAA	biomesoplenty{6.1.0.2222} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2222-universal.jar) 
	UCHIJAAAA	cyclicmagic{1.4.7} [Cyclic] (Cyclic-1.11.2-1.4.7.jar) 
	UCHIJAAAA	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide-API-1.11.2-2.1.1-52.jar) 
	UCHIJAAAA	bloodmagic{1.11-2.1.10-79} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.10-79.jar) 
	UCHIJAAAA	botania{r1.9-343} [Botania] (Botania r1.9-343.jar) 
	UCHIJAAAA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJAAAA	chesttransporter{2.7.9} [Chest Transporter] (ChestTransporter-1.11.2-2.7.9.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.10.14} [Chisel] (Chisel-MC1.11.2-0.0.10.14.jar) 
	UCHIJAAAA	cyclopscore{0.10.3} [Cyclops Core] (CyclopsCore-1.11.2-0.10.3.jar) 
	UCHIJAAAA	commoncapabilities{1.3.3} [CommonCapabilities] (CommonCapabilities-1.11.2-1.3.3.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJAAAA	crafttweaker{3.0.25} [Crafttweaker] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJAAAA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	forestry{5.3.4.99} [Forestry] (forestry_1.11.2-5.3.4.99.jar) 
	UCHIJAAAA	eleccore{1.7.420} [ElecCore] (ElecCore-1.11-1.7.420.jar) 
	UCHIJAAAA	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.1x-1.4.8.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.11.2.jar) 
	UCHIJAAAA	dsurround{3.4.5.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.0.jar) 
	UCHIJAAAA	presets{3.4.5.0} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.5.0.jar) 
	UCHIJAAAA	elevatorid{1.3.1} [Elevator Mod] (ElevatorMod-1.11.2-1.3.1.jar) 
	UCHIJAAAA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UCHIJAAAA	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UCHIJAAAA	etlunar{1.11.2-0.11.0c} [ET Lunar] (etlunar-1.11.2-0.11.0c.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.1.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	reborncore{2.14.2.94} [Reborn Core] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.14.2.94} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.14.2.94-universal.jar) 
	UCHIJAAAA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.1.59.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	refinedstorage{1.4.6} [Refined Storage] (refinedstorage-1.4.6.jar) 
	UCHIJAAAA	growablecells{1.0.2} [Growable Cells] (Growable Cells-1.11.2-1.0.2.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-2.0.1.jar) 
	UCHIJAAAA	initialinventory{2.0.2} [InitialInventory] (InitialInventory-2.0.2.jar) 
	UCHIJAAAA	inventorytweaks{1.62+beta.89.be6ffe4} [Inventory Tweaks] (InventoryTweaks-1.62+beta.89.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.19.803} [Iron Chest] (ironchest-1.11.2-7.0.19.803.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	magicbees{1.0} [MagicBees] (MagicBees-Alpha-1.0.1.jar) 
	UCHIJAAAA	missing_pieces{4.2.1} [Missing Pieces] (missing_pieces-1.11.2-4.2.1.jar) 
	UCHIJAAAA	morebees{1.11.2-1.3.2} [More Bees] (morebees-1.11.2-1.3.2.jar) 
	UCHIJAAAA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.11.2.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.5.4} [Mystical Agriculture] (mysticalagriculture[1.11.2]-1.5.4.jar) 
	UCHIJAAAA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJAAAA	omlib{1.11.2-3.0.0-94} [OMLib] (omlib-1.11.2-3.0.0-94.jar) 
	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-153} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-153.jar) 
	UCHIJAAAA	fodc{1.10.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.10.0.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJAAAA	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCHIJAAAA	jp.crafterkina.pipes{1.1.0.12} [Pipes] (Pipes-1.11-1.1.0.12.jar) 
	UCHIJAAAA	quantumstorage{4.2.2} [QuantumStorage] (QuantumStorage-1.11.2-4.2.2.jar) 
	UCHIJAAAA	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	roots{0.017} [Roots 2] (roots-2-0.017.jar) 
	UCHIJAAAA	ruins{16.4} [Ruins Mod] (Ruins-1.11.2.jar) 
	UCHIJAAAA	silentlib{2.1.3} [Silent Lib] (SilentLib-1.11.x-2.1.3-58.jar) 
	UCHIJAAAA	silentgems{2.3.12} [Silent's Gems] (SilentsGems-1.11.x-2.3.12-178.jar) 
	UCHIJAAAA	solarfluxreborn{2.15r} [Solar Flux Reborn] (SolarFluxReborn_1.11.2-2.15r.jar) 
	UCHIJAAAA	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.6} [Storage Drawers] (StorageDrawers-1.11.2-4.2.6.jar) 
	UCHIJAAAA	subcommonlib{1.1.4.1} [Subaraki's Common Library] (sublib-1.11.2-1.1.4.1.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.89} [Super Crafting Frame] (supercraftingframe-1.11-1.2.1.89.jar) 
	UCHIJAAAA	techreborn{2.2.1.142} [Tech Reborn] (TechReborn-1.11.2-2.2.1.142-universal.jar) 
	UCHIJAAAA	telepads{1.11.2-1.0.2.0} [Telepads] (telepads-1.11.2-1.0.2.0.jar) 
	UCHIJAAAA	theoneprobe{1.4.7} [The One Probe] (theoneprobe-1.1x-1.4.7.jar) 
	UCHIJAAAA	topaddons{1.11.2-0.13.0} [TOP Addons] (topaddons-1.11.2-0.13.0.jar) 
	UCHIJAAAA	torchmaster{1.3.3.37} [TorchMaster] (torchmaster_1.11.2-1.3.3.37.jar) 
	UCHIJAAAA	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar) 
	UCHIJAAAA	yabba{1.11.2-0.5.1} [YABBA] (YABBA-1.11.2-0.5.1.jar) 
	Loaded coremods (and transformers): 
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
ChiselCorePlugin (Chisel-MC1.11.2-0.0.10.14.jar)
  team.chisel.common.asm.ChiselTransformer
RebornCoreASM (RebornCore-1.11.2-2.14.2.94-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
SFRCore (SolarFluxReborn_1.11.2-2.15r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (Quark-r1.2-92.jar)
  vazkii.quark.base.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.6.1.59.jar)
  
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
HammerCoreCore (HammerCore_1.11.2-1.6.7.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r108.jar
		* AppleCoreAPI (2.2.0) from AppleCore-mc1.11.2-2.1.2.jar
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.4.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.2-92.jar
		* bloodmagic|API (1.11-2.1.10-79) from BloodMagic-1.11-2.1.10-79.jar
		* BotaniaAPI (86) from Botania r1.9-343.jar
		* chesttransporter|api (1) from ChestTransporter-1.11.2-2.7.9.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.10.14.jar
		* CoFHAPI (1.8.9R1.2.0B1) from FluxedRedstone-2.6.1.59.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from theoneprobe-1.1x-1.4.7.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.4.1.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.11.2-1.3.3.jar
		* compatlayer (0.2.9) from compatlayer-1.11.2-0.2.9.jar
		* CSLib|API (0.3.0) from Decocraft-2.4.2_1.11.2.jar
		* DLDungeonsAPI (1.1) from DoomlikeDungeons-1.9.2-MC1.11.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.8.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.420.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.420.jar
		* environmentaltech-api (1.11.2-0.11.0d) from environmentaltech-1.11.2-0.11.0d.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.4.99.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.4.99.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.11.2-2.1.1-52.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.6.jar
		* jp.crafterkina.pipes.api (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.pipe (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.render (1.0) from Pipes-1.11-1.1.0.12.jar
		* JustEnoughItemsAPI (4.12.0) from jei_1.11.2-4.3.5.277.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* reborncoreAPI (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Fuel (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Power (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Recipe (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* reborncoreAPI|Tile (2.14.2.94) from RebornCore-1.11.2-2.14.2.94-universal.jar
		* SilentGemsAPI (3) from SilentsGems-1.11.x-2.3.12-178.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.4.6.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.6.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.6.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.6.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.4.6.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.6.jar
		* techrebornAPI (2.2.1.142) from TechReborn-1.11.2-2.2.1.142-universal.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.7.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0c.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.14.2.94
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Gucky2000'/221, l='Insel 01', x=-183.50, y=63.00, z=424.78]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Lach01298** [comment]
Ran 9 alverays for an hour and they seem to be fine getting swarm hives with rocky queens.
so can not confirm. sorry.
