### ISSUE TITLE
1.10.2 Spec Produce not working?

### ISSUE THREAD

**Issue by LoonPie** [Lach01298/MoreBees#47]
So i was wondering if the Spec Produce of Bees like the Wither Queen and Apocalyptic Queen are not working or sth with the rate is not right? Capped both with Gendustry to Temp and Humidity Tolerance 0 and even put them directly in the Nether instead of using Hell emulation upgrade in the Industrial Apiary.
Apocalyptic Queen produced 5 1/2 Stacks of Simmering Comb (Which has 30%) but not a Single Gunpowder (20%) Blaze Powder (20%) or Ghast Tear (5%) and the same goes for the Wither Queen, not a single Nether Star Fragment (3%) but more than 5 stacks of Withering Combs (35%)

**Comment by Lach01298** [comment]
Did you out a wither skull on the wither bees and TNT under the apocalyptic? if you didn't know this information there is a wiki that says it on this github
