### ISSUE TITLE
[1.11.2] Crash between Initialization and Postinitalization

### ISSUE THREAD

**Issue by MasterEnderman** [Lach01298/MoreBees#49]
Everytime booting up my modpack, it crashes at the exact same point.

Crash-Report: [Crash-Report](https://pastebin.com/YNCwsvzc)
FML-log: [FML-log](https://pastebin.com/UE9FDx7U)

More Bees: 1.11.2_1.4.1
Forestry: 1.11.2-5.3.4.101
Forge: 13.20.0.2315

**Comment by Lach01298** [comment]
So what mods do you have installed that add platinum?

**Comment by MasterEnderman** [comment]
Thanks for the fast reply.
I guess it would be [Silent's gems: Extra Parts](https://minecraft.curseforge.com/projects/silents-gems-extra-parts) adding the Platinum, but on an other instance i got them working together. What could cause this?

EDIT: fixed it by adding another mod, which adds Platinium Dust. The dust is now used as a bee product.

**Comment by Shorty9385** [comment]
What mod did you add? I am having the same issue, and I have silent gems extra parts as well.

**Comment by MasterEnderman** [comment]
I added Thermal Foundation, which adds a dust for nearly every metal in the game.
The problem is that silent gems extra parts doesn't add a dust version of platinum.
