### ISSUE TITLE
Suggestion: Update to 1.12

### ISSUE THREAD

**Issue by Kris1432** [Lach01298/MoreBees#50]
Would be great to see this mod ported to 1.12 now a lot of mods are pushing that way.

**Comment by CatAndHorse** [comment]
+1

**Comment by Kris1432** [comment]
don't worry, Binnie's Mods will get to 1.12 before this.

**Comment by trilexcom** [comment]
+1 too

**Comment by Lach01298** [comment]
I'm trying to update to 1.12 but it seems to have changed a lot and also i'm fairly busy at the moment so sorry for the inconvenience

**Comment by marcin212** [comment]
#56

**Comment by Kris1432** [comment]
lol, ok haha, fair enough, no conflicts with Binnie's mods? @marcin212
