### ISSUE TITLE
Metallic Grains

### ISSUE THREAD

**Issue by Guus643** [Lach01298/MoreBees#51]
Using FTB: Beyond pack, the metallic grains received from metallic propollis no longer has any uses.  Until upgrading to the 1.9 version of beyond, I was able to make cobalt and ardite from it.

**Comment by Lach01298** [comment]
Not my problem that they disable the recipes they are used for you should contact them.

**Comment by Guus643** [comment]
Thanks for the response, but you have to remember your audience.  People who don't mod minecraft have no idea who to contact about things when they stop working.  Saying 'not my problem, contact them' isn't helpful to the average player.  The only thing a player knows is that an item you added no longer has a use... they don't what the cause is.  I'm not even sure who you mean by 'them'.  The mod pack authors?  The server owners?

**Comment by Lach01298** [comment]
yeah sorry for the harsh response. Generally i would say the better thing to do is test the mod out of a mod pack to see if it works because things like minetweaker can be added to mod packs to change and disable recipes. But i do get this is probably not easy for everyone to do.

**Comment by MasterEnderman** [comment]
I have the same Problem with a custom Modpack. I didn't change any recipes for Forestry or More Bees but the metallic grains still don't have any use.
