### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by Obbi89** [Lach01298/MoreBees#52]
Hey there is a small typo here:
https://github.com/Lach01298/MoreBees/blob/master/src/main/resources/assets/morebees/lang/en_US.lang#L86
It should be ura*n*ium.

**Comment by Tencao** [comment]
Fixed in https://github.com/Tencao/MoreBees/commit/88f10ae0c95ca69dc8c58d6dce9126afb8b3b2ce
