### ISSUE TITLE
Suggestion : Chrome, Zinc, Tungsten, Titanium, Mana Infused/Mithril, and Alloy Bees

### ISSUE THREAD

**Issue by Abespadold** [Lach01298/MoreBees#53]
Everything is in the title. For Alloy Bees, for exemple, a Cobalt Princess with an Ardite Drone could lead to a Manyullyn Queen, or a Withering princess (or every other bees that produce coal) with an Iron drone could evolve in a steel queen, etc...

**Comment by Lach01298** [comment]
Element bees maybe alloy bees no for the same reason as i said here https://github.com/Lach01298/MoreBees/issues/39
