### ISSUE TITLE
[more bees 1.10.2.1.4.1.1] [forge-12.18.3.2316] [forestry 1.10.2-5.2.17.381] Bees not producing their specialty regardless of correct temperature / humidity 

### ISSUE THREAD

**Issue by OfficerLovejoy** [Lach01298/MoreBees#54]
Playing the current Age of Engineering Modpack but have also run into this issue on FTB-Beyond.
My bees are just not producing their specialty regardless of the correct temperature / humidity.
And i tried setting it up in the correct biome, simulating the correct t/h in an alveary and even tried it with a biome changer in an industrial apiary on ftb beyond.
I am at a loss here.
![image](https://user-images.githubusercontent.com/5771746/28867422-60d14a70-7776-11e7-8ddf-04d13891c02c.png)
![image](https://user-images.githubusercontent.com/5771746/28867437-6f759126-7776-11e7-8ea8-2049a73617c5.png)
I have let this setup run for around 30 generations and have not gotten 1 emerald fragment.
Same issue with the apocalyptic bee and i suppose the withering bee will be no different.

**Comment by MasterEnderman** [comment]
You need to place a specific block under the apiary. 

An emerald block for the emerald queen. 
A diamond block for the diamond queen. 
A tnt block for the apocalyptic queen. 

There is a wiki where it shows the required block.

**Comment by OfficerLovejoy** [comment]
fk me, that was it.
Also found the wiki, after i knew what i had to look for:
https://github.com/Lach01298/MoreBees/wiki/Bee-Species#wither-1

Thank you sir, this is a huge relief.
