### ISSUE TITLE
Issues with Binnie's Mods

### ISSUE THREAD

**Issue by jjc54** [Lach01298/MoreBees#55]
Forge: forge-13.20.1.2393
Forestry: forestry_1.11.2-5.3.4.155
Binnie's Mods: binnie-mods-1.11.2-2.1.0.34
More Bees: morebees-1.11.2-1.4.1
Crash report: https://pastebin.com/E9NGmUZp

This crash happened upon startup. I'm also attempting to disable extrabees in favor of more bees but that doesn't seem to stop the crash. I'm unsure if this is a problem here or with genetics, but there's bound to be a bunch of issues popping up between the two so I just wanted to go ahead and get the conversation started.

**Comment by marcin212** [comment]
Fixed in 1.12.1 https://github.com/Lach01298/MoreBees/commit/6574a0622302f3ae03374e1eb04ac7f271f8e88b
