### ISSUE TITLE
boggy bees do not create peat

### ISSUE THREAD

**Issue by soulreaper261** [Lach01298/MoreBees#57]
after breeding boggy bees all they do is make mossy combs but peat is never created

**Comment by jjc54** [comment]
Are the bees in the right biome? They will only make their speciality (peat) if they are in a suitable biome or if they are being manipulated in alvearies/greenhouses.

**Comment by soulreaper261** [comment]
they are being manipulated with gendustry but still nothing

**Comment by jjc54** [comment]
Hmm are you using the biome simulator upgrades or genetic manipulation?

**Comment by jjc54** [comment]
I would go into single-player and see if they work in a regular apiary in a swamp biome. If not, its a morebees issue but if they work it could be a gendustry issue.

**Comment by Lach01298** [comment]
i don't add boggy bees
