### ISSUE TITLE
[1.12.1] Crash on Startup

### ISSUE THREAD

**Issue by Kris1432** [Lach01298/MoreBees#59]
Forge: 2460
Version: 1.12.2-1.4.2

Cause: Startup Crash

Crashlog: https://pastebin.com/DBLPbWiF

cc @marcin212

**Comment by marcin212** [comment]
Hmmm, a compat with some mod turned on and didn't find an ore in OreDict

**Comment by Lach01298** [comment]
strange just checked it and it seems deep resonance has remove resonating ore from the ore dictionary. I sort of would say this is deep resonances problem if they don't use the ore dictionary i cant support the mod. but i can make it so the config makes it not load. so you can use deep resonance with the mod but no resonating bees

**Comment by frank89722** [comment]
https://github.com/McJty/DeepResonance/issues/223

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/b99a40b2a542864425cfbe34d60b0103

Same here, if it helps.

**Comment by Tencao** [comment]
Fixed in this commit https://github.com/Tencao/MoreBees/commit/88f10ae0c95ca69dc8c58d6dce9126afb8b3b2ce
