### ISSUE TITLE
Bees with a twist

### ISSUE THREAD

**Issue by McBossKiller** [Lach01298/MoreBees#6]
I thought of an interesting idea of having bees that produce energy such as EU and RF, also i thought of an idea of having bees with the main purpose of attacking mobs, but not the player, like giving them an effect that will cause damage to mobs, but not the player, You could move farther along a path of the bee to make it release a stronger and stronger effect.

**Comment by Lach01298** [comment]
power no, things(item/liquids) to produce power sure.
attacking bees, well the heroic already does this. you better than heroic? I suggest better defense than bees
