### ISSUE TITLE
1.12 conflict crash with Binnie's mod

### ISSUE THREAD

**Issue by Zygus42** [Lach01298/MoreBees#60]
forestry_1.12.1-5.5.0.178
forestry-binnie-mods-1.12.1-2.3.0.60
forestry-morebees-1.12.2-1.4.2
[crash-2017-08-30_13.42.39-client.txt](https://github.com/Lach01298/MoreBees/files/1262522/crash-2017-08-30_13.42.39-client.txt)

Also reported on Binnie's mod.

**Comment by Tencao** [comment]
Is this still an issue on the latest version?

**Comment by Tencao** [comment]
Should be fixed in https://github.com/Tencao/MoreBees/commit/6516e032fb4989ab3af25a7c0cfbce4d7f621aec , Please reopen if the issue reoccurs
