### ISSUE TITLE
[suggestion] change naming convention of jar

### ISSUE THREAD

**Issue by Zygus42** [Lach01298/MoreBees#61]
It would help mod pack developers a lot to have your mod with the "forestry-" prefix so that all forestry related mods sorted together in the mods folder.  ie:
        forestry-morebees-1.12.2-1.4.2.jar
instead of
        morebees-1.12.2-1.4.2.jar

**Comment by Lach01298** [comment]
i don't see why none of the other forestry addons do

**Comment by Zygus42** [comment]
Which is why I posted this suggestion on each of the other addons, and if that's the only reason you have for summarily turning down a perfectly sensible idea, that's just sad.
