### ISSUE TITLE
1.12 incompatibility with JEI Bees mod

### ISSUE THREAD

**Issue by Zygus42** [Lach01298/MoreBees#62]
Am hoping to use the following mods:
forestry_1.12.1-5.5.0.178
forestry-MagicBees-1.12-3.1.5
forestry-binnie-mods-1.12.1-2.3.0.60
forestry-morebees-1.12.2-1.4.2

and the JEI Bees mod to be able to see the breeding etc (jeibees-0.9.0.2-mc1.12).  

JEI Bees works with any and all combinations of the mods above, until your mod is included in the mix, and then it no longer shows any info on any of the mod's bees including base forestry.  Have included a log on the theory that it may help:

[fml-client-latest.txt](https://github.com/Lach01298/MoreBees/files/1263690/fml-client-latest.txt)

**Comment by Tencao** [comment]
Is this still an issue on the latest versions?

**Comment by bretbelgarde** [comment]
This happens for me with the 1.4.3 version.
Running with:
Forge - 14.23.1.2555
Forestry - 5.7.0.214
JEI -  4.8.0.114
JEI Bees - 0.9.0.5

Without MoreBees JEI Bees functions as expected.
When MoreBees is added JEI fails to load the JEI Bees plugin.

[fml-client-latest.log](https://github.com/Tencao/MoreBees/files/1523563/fml-client-latest.log)

**Comment by Tencao** [comment]
Fixed in https://github.com/Tencao/MoreBees/commit/6516e032fb4989ab3af25a7c0cfbce4d7f621aec
