### ISSUE TITLE
Exception Errors 1.12.1

### ISSUE THREAD

**Issue by Bearmanic** [Lach01298/MoreBees#64]
When loading Minecraft I receive the following error:

 
[crash-2017-09-08_21.31.33-client.txt](https://github.com/Lach01298/MoreBees/files/1289844/crash-2017-09-08_21.31.33-client.txt)

**Comment by OneEyeMaker** [comment]
The same issue.
@Lach01298 
OreDictionary may have **_no entries_** with selected tag, so getting *first entry* causes crash.

**Comment by DeadSix27** [comment]
Yep, same issue: Yet another stacktrace if it helps: https://gist.github.com/DeadSix27/029a176716bad78a5de7ece1507a8353

**Comment by Tencao** [comment]
Fixed the crash with deepresonance, as it seems their oredict was removed, so an additional workaround has been placed. https://github.com/Tencao/MoreBees/commit/88f10ae0c95ca69dc8c58d6dce9126afb8b3b2ce
