### ISSUE TITLE
[1.11.2 crash] More bees Crashes the game (Binnies mod related)

### ISSUE THREAD

**Issue by darkmtbg2** [Lach01298/MoreBees#65]
More bees crashes Minecraft if Binnies mods are present With an initialization error
Removing the mod(s) that Binnies mods are part of doesn't crash
(Disabling Magic bees and Elec core doesn't do anything)
https://pastebin.com/SQ5rN5MX

**Comment by Tencao** [comment]
Should be fixed in dev
