### ISSUE TITLE
Wiki error on frames

### ISSUE THREAD

**Issue by kdb424** [Lach01298/MoreBees#66]
From your own code, values are different in several places

frameSweet = register(new ItemFrame(120, 1.1f, 2.5f, 1.0f, 0.5f, "frameSweet"));
frameCooled = register(new ItemFrame(300, 2.0f, 3.5f, 0.8f, 0.25f, "frameCooled"));
frameMutating = register(new ItemFrame(240, 1.5f, 0.9f, 1.0f, 3.0f, "frameMutating"));

https://github.com/Lach01298/MoreBees/wiki/Frames

The Mutating frame is what caught my attention.

**Comment by Lach01298** [comment]
Woops thats a typo on the wiki
