### ISSUE TITLE
[MC 1.12.2] More Bees 1.12.2-1.4.2 works but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [Lach01298/MoreBees#67]
[More Bees 1.12.2-1.4.2](https://minecraft.curseforge.com/projects/more-bees/files/2469187) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by axieum** [comment]
Broken with latest Forestry; reference Issue #68.

**Comment by Tencao** [comment]
This should no longer be an issue as of 1.4.3, if it is, please reopen this.

**Comment by sandalle** [comment]
Thank you @Tencao . :)
