### ISSUE TITLE
[1.10.2] Ardite and Cobalt bees can't work in any biome

### ISSUE THREAD

**Issue by teser1** [Lach01298/MoreBees#77]
These bees require hellish biome and daylight which is an impossible scenario without an alveary lighting block from Extra Bees or a hellish simulator from Gendustry.  These bees are impossible to work with just Forestry/More Bees installed because there is no way to simulate a hellish biome in the overworld or daylight in the nether, and they can't tolerate any temperature less then hellish by default.  They need to be made nocturnal by default in order to work in the nether.

For the moment the only workaround I've found is to cross breed the drones with a princess that has the nocturnal trait and add the trait that way, however freshly bred princess's/queens are completely useless.

**Comment by Tencao** [comment]
I'll look into this and see about changing the required daylight trait

**Comment by Tencao** [comment]
This should no longer be the case on newer versions of morebees
