### ISSUE TITLE
Mod Id's

### ISSUE THREAD

**Issue by bookerthegeek** [Lach01298/MoreBees#78]
## Heyo! ##

Saw the following in the logs, should be an easy fix... Just thought I would let you know.
```
[main/ERROR] [FML]: Unable to parse dependency for mod 'morebees' with dependency string 'after:IndustrialCraft2'. The modId 'IndustrialCraft2' must be all lowercase.
```

### Versions ###
- Minecraft: 1.12.2
- MoreBees 1.4.4
- IndustrialCraft 2 2.8.58-ex112
- Forestry 5.8.0.250

**Comment by Tencao** [comment]
As far as I know in the upcoming build there is no dependency for IC2, so I'm going to mark this as fixed
