### ISSUE TITLE
I got a crash when loading in 1.12.2

### ISSUE THREAD

**Issue by ghost** [Lach01298/MoreBees#80]
MagicBees-1.12.2-3.1.10.jar
forge-14.23.4.2707
Crashes near the end of loading the modpack.
[crash-2018-06-10_09.42.10-client.txt](https://github.com/Tencao/MoreBees/files/2088048/crash-2018-06-10_09.42.10-client.txt)

**Comment by ravenwing210** [comment]
I've gotten the same error, seems to be coming from an interaction with EnderIO as removing that stopped the crash.

**Comment by Rikshy** [comment]
You sure @PurpleRavenX11? i don't have enderIO in my pack and it still crashes the same way

**Comment by Tencao** [comment]
I'm going to try and push a build out later today that has this issue fixed

**Comment by Tencao** [comment]
Could you try the latest build and see if the issue is still present?

**Comment by Rikshy** [comment]
already did, no more crashes :)

Thanks!
