### ISSUE TITLE
Crash when breaking a bee hive

### ISSUE THREAD

**Issue by ghost** [Lach01298/MoreBees#81]
Right-click with a destroy wand from Extra utils 2 on a beehive and crashed to desktop.

https://gist.github.com/TacticalUniverse/ed587f284c18fa8f5c0cd771808fd031

https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/15

**Comment by Tencao** [comment]
This looks like a bug with foamfix or forestry, please report it there first.
