### ISSUE TITLE
No Bee Breeding recipes for Resonating and Uranic Bees.

### ISSUE THREAD

**Issue by remclave** [Lach01298/MoreBees#84]
Forestry Version: 384
More Bees Version: 2.0.1
Forge Version: 2760

Don't know if the recipes are simply missing or if there is a conflict with some other mod disabling the recipes. But I cannot find the Bee Breeding recipes for the Resonating or Uranic Bees. I know they have recipes listed in your Wiki but they are not showing up in-game. Not certain if you need any other information to help.

Thank you for any assistance in this issue.

**Comment by NimonoSolenze** [comment]
Resonating Bees require Deep Resonance to be installed. Not sure about Uranium Bees, probably IC2 from the sounds of it.
